### ISSUE TITLE
振動機能をつける

### ISSUE THREAD

**Issue by Yanai1005** [jyogi-web/yanbaru-back-joycon#11]

**Comment by KOU050223** [comment]
難しそう？
あまり記事がないのと、PyJoyconは情報取るくらいしかできなさそう

joyconのレポートのレポート
https://www.amusement-creators.info/articles/advent_calendar/2019/23_0/

joyconのレポート記事
https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering?tab=readme-ov-file

**Comment by Yanai1005** [comment]
データを取得できるがこっちからデータを行うのが難しそうなので閉幕
