### ISSUE TITLE
デプロイ方法を考える

### ISSUE THREAD

**Issue by Yanai1005** [jyogi-web/yanbaru-back-joycon#8]

**Comment by Yanai1005** [comment]
Flask？

**Comment by Yanai1005** [comment]
Azure
https://learn.microsoft.com/ja-jp/azure/app-service/quickstart-python?tabs=flask%2Cwindows%2Cazure-cli%2Cazure-cli-deploy%2Cdeploy-instructions-azportal%2Cterminal-bash%2Cdeploy-instructions-zip-azcli

**Comment by KOU050223** [comment]
https://justdance-beb9gtdedwgxhydx.japaneast-01.azurewebsites.net/
flaskのデプロイ自体はできるが、デプロイした先でどのようにbluetooth接続してデータがとるかが問題
というか知らない

**Comment by Yanai1005** [comment]
AzureのようなクラウドではBluetooth接続ができないので諦めます

**Comment by Yanai1005** [comment]
Localでの完成を目指す

**Comment by Yanai1005** [comment]
他のデバイス（ラズパイ）などを使ってAzure IoT HubやAzure IoT Centralなどのクラウドサービスと連携すれば、JoyconのBluetooth接続でも可能
